version: '3.8'

services:
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: app:8080
      SERVERNAME: app:8080
      EXTRANAMES: app:8080,test2.example.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"

  app:
    image: 'docker-springboot-pg-trackmyroute:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - nginx-ssl-proxy
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/trackmyroute
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=trackmyroute
    ports:
      - "5432:5432"

